export const images = [
  './ki1.webp',
  './ki2.webp',
  './ki3.webp',
  './ki4.webp',
  './ki5.webp',
  './ki6.webp',
  './ki7.webp',
  './ki8.webp',
  './ki9.webp',
  './ki10.webp',
  './ki11.webp',
  './ki12.webp',
  './ki113.webp',
  './ki15.webp',
  './ki16.webp',
  './ki17.webp',
];
